# Generated by Django 3.0.3 on 2020-03-23 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_auto_20200323_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='time',
            new_name='timer',
        ),
    ]
